apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  namespace: default
  labels:
    app: netshoot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot:latest
        command: 
          - /bin/bash
          - -c
          - "while true; do sleep 3600; done"  # Keep container running
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
